registry:
  # Docker registry url
  url: http://192.168.2.50:5000/v2/_catalog
  # Docker registry fqdn
  name: localhost:5000
  # To allow image delete, should be false
  readonly: false
  auth:
    # Disable authentication
    enabled: false