kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: ngx
  name: ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ngx
  template:
    metadata:
      labels:
        k8s-app: ngx
    spec:
      containers:
        - name: ngx
          image: nginx:latest
          ports:
            - containerPort: 8000
              protocol: TCP